### ISSUE TITLE
Updating apollo-boost 0.1.4 to 0.1.16 (latest) breaks vote caching

### ISSUE THREAD

**Issue by DanielASAndrews** [howtographql/react-apollo#61] opened 2018-10-17 19:33 UTC
_Note: This issue occurs with a newer version of apollo-boost (0.1.4) in use , current version used in the app works as intended_

I was investigating why vote changes didn't update properly in the UI and isolated the issue to apollo-boost

**How to Reproduce:** 

Update _apollo-boost_ to latest (currently 0.1.16), and up vote any link, you will notice the change is not reflected in the UI as React doesn't end up calling render for the Link component.  The Prisma server is updated as it's supposed to, and if you refresh the page, you will see the correct vote count for the link.  The store also looks to be updated correctly, but React is not detecting the change to re-render.

**Comment by galanis-a** [comment] 2018-10-20 20:32
I am getting this behaviour with apollo-boost 0.1.4

**Comment by swcarlosrj** [comment] 2019-02-06 11:01
Thanks @DanielASAndrews for opening this issue 😄. It should be working now. Closing this, please, feel free to re-open this issue if you cannot make it work!

**Closed by swcarlosrj** 2019-02-06 11:01 UTC

**Comment by SnekNOTSnake** [comment] 2020-06-24 15:23
This issue reoccurred. But in my case, the problem is with `react-apollo` >2.5 (including the beta version 3.0). `react-apollo` <=2.5 is fine.
Spent a good couple of hours finding the problem (I'm new to things like these 😅️).
