### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by MisinformedDNA** [howtographql/react-apollo#40] opened 2018-04-02 15:43 UTC
This first error is around `...req`. At first it looks like a typo, but it's liste as such in the tutorial, README.md and the tar.gz file. But if it was a type, I deleted the `...` and retried. But then it complained about the `function` keyword.

> PS D:\PoCs\hackernews-react-apollo\server> yarn dev
> yarn run v1.5.1
> warning package.json: No license field
> $ npm-run-all --parallel start playground
> warning package.json: No license field
> $ node src/index.js
> warning package.json: No license field
> $ graphql playground
> D:\PoCs\hackernews-react-apollo\server\src\index.js:19
>     ...req,
>     ^^^
> 
> SyntaxError: Unexpected token ...
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Module._compile (module.js:542:28)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:389:7)
>     at startup (bootstrap_node.js:149:9)
> error An unexpected error occurred: "Command failed.
> Exit code: 1
> Command: C:\\WINDOWS\\system32\\cmd.exe
> Arguments: /d /s /c node src/index.js
> Directory: D:\\PoCs\\hackernews-react-apollo\\server
> Output:
> ".
> info If you think this is a bug, please open a bug report with the information provided in "D:\\PoCs\\hackernews-react-apollo\\server\\yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ERROR: "start" exited with 1.
> error An unexpected error occurred: "Command failed.
> Exit code: 1
> Command: C:\\WINDOWS\\system32\\cmd.exe
> Arguments: /d /s /c npm-run-all --parallel start playground
> Directory: D:\\PoCs\\hackernews-react-apollo\\server
> Output:
> ".
> info If you think this is a bug, please open a bug report with the information provided in "D:\\PoCs\\hackernews-react-apollo\\server\\yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

> PS D:\PoCs\hackernews-react-apollo\server> yarn dev
> yarn run v1.5.1
> warning package.json: No license field
> $ npm-run-all --parallel start playground
> warning package.json: No license field
> $ node src/index.js
> warning package.json: No license field
> $ graphql playground
> D:\PoCs\hackernews-react-apollo\server\src\resolvers\Query.js:1
> (function (exports, require, module, __filename, __dirname) { async function feed(parent, args, ctx, info) {
>                                                                     ^^^^^^^^
> 
> SyntaxError: Unexpected token function
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Module._compile (module.js:542:28)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (D:\PoCs\hackernews-react-apollo\server\src\index.js:3:15)
> error An unexpected error occurred: "Command failed.
> Exit code: 1
> Command: C:\\WINDOWS\\system32\\cmd.exe
> Arguments: /d /s /c node src/index.js
> Directory: D:\\PoCs\\hackernews-react-apollo\\server
> Output:
> ".
> info If you think this is a bug, please open a bug report with the information provided in "D:\\PoCs\\hackernews-react-apollo\\server\\yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ERROR: "start" exited with 1.
> error An unexpected error occurred: "Command failed.
> Exit code: 1
> Command: C:\\WINDOWS\\system32\\cmd.exe
> Arguments: /d /s /c npm-run-all --parallel start playground
> Directory: D:\\PoCs\\hackernews-react-apollo\\server
> Output:
> ".
> info If you think this is a bug, please open a bug report with the information provided in "D:\\PoCs\\hackernews-react-apollo\\server\\yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Any ideas on how to get this working? As the recommended tutorial, I'm not sure where to turn next.

[yarn-error.log](https://github.com/howtographql/react-apollo/files/1868489/yarn-error.log)

**Comment by ssimpson89** [comment] 2018-04-03 19:37
I seem to be having the same issue as well. Would love to hear a solution!

**Comment by ssimpson89** [comment] 2018-04-03 20:36
It would help if I was on the latest version! The CentOS repo is awfully old. Upgraded to LTS version and this is now running fine.

**Comment by haeke** [comment] 2018-04-09 15:17
Hello - I've run into this error and it happened to be because I was running an older version of Node. I can confirm that it is working on Node version 9.11.1.

**Comment by MisinformedDNA** [comment] 2018-04-10 19:16
The documentation should be updated to require a minimum version, which [apparently](https://stackoverflow.com/a/40528360/1152054) is NodeJS 6.

**Comment by JingyuZ** [comment] 2018-05-21 04:16
Run into the same issue and upgraded to latest Node version solved it. I think the issue is node 6 doesn't support spread operator for objects (only for arrays and iterables), and node 8.3 started to support it: https://stackoverflow.com/questions/40066731/node-v6-failing-on-object-spread?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by swcarlosrj** [comment] 2019-02-06 11:06
Thanks @MisinformedDNA for opening this issue 😄. It should be working now. Closing this, please, feel free to re-open this issue if you cannot make it work!

**Closed by swcarlosrj** 2019-02-06 11:06 UTC
Labels: 🔎Needs Investigation
